SELECT row_number() OVER (ORDER BY p.pollutant_cas_id) AS id,
    er.id AS report_id,
    fs.alt_site_identifier AS facility_site_id,
    er.year AS inventory_year,
    eu.unit_identifier AS emissions_unit_id,
    eu.description AS emission_unit_description,
    ep.emissions_process_identifier AS process_id,
    ep.description AS process_description,
    p.pollutant_name,
    repcode.short_name AS reporting_period_type,
    repper.calculation_parameter_value AS throughput_value,
    repper.calculation_parameter_uom AS throughput_uom,
	cmc.description AS emission_calc_method,
    e.emissions_uom_code,
    e.emissions_numerator_uom,
    e.emissions_denominator_uom,
    e.emissions_factor,
    e.last_modified_by,
    e.last_modified_date,
    replace(e.emissions_factor_text::text, ','::text, ''::text) AS emissions_factor_text,
    replace(e.comments::text, ','::text, ''::text) AS emissions_comment,