server:
  use-forward-headers: true
  servlet:
    context-path: /cef-web
spring:
  profiles:
    active: dev
  jmx.enabled: false
  thymeleaf:
      mode: HTML  
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate:
      # disables annoying non-error in logs from hibernate
      jdbc.lob.non_contextual_creation: true
      # register custom PostgreSQL dialect that supports jsonb
      dialect: gov.epa.cef.web.hibernate.PostgreSQLDialectWithJsonSupport
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/CEF"
    username: cef
    password: password
cdx:
  registerEndpointConfiguration:
    serviceUrl: https://devngn.epacdxnode.net/cdx-register-II/services/RegisterService
    operatorId: caer-cef-admin@epa.gov
    operatorPassword: CDXcaercef01
  registerProgramFacilityEndpointConfiguration:
    serviceUrl: https://devngn.epacdxnode.net/cdx-register-II/services/RegisterProgramFacilityService
    operatorId: caer-cef-admin@epa.gov
    operatorPassword: CDXcaercef01