server:
  use-forward-headers: true
  servlet:
    context-path: /cef-web
    session:
      cookie:
        http-only: true
        secure: true
spring:
  profiles:
    active: #spring.profiles.active#
  servlet.multipart.max-file-size: 100MB
  servlet.multipart.max-request-size: 105MB
  jmx.enabled: false
  hazelcast:
    config: classpath:cef-hazelcast-cache.xml
  thymeleaf:
    mode: HTML
  mvc:
    async:
      request-timeout: 120000
  jpa:
      # 14:48:39.624-05 WARN  [...JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration]
      # spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering.
      # Explicitly configure spring.jpa.open-in-view to disable this warning
      # TODO: Remove anti-pattern by switching to DTO and adding to *all* ServiceImpl using a Repository a @Transactional
    #open-in-view: false
    show-sql: false
    generate-ddl: false
    properties.hibernate:
      # disables annoying non-error in logs from hibernate
      jdbc.lob.non_contextual_creation: true
      # register custom PostgreSQL dialect that supports jsonb
      dialect: gov.epa.cef.web.hibernate.PostgreSQLDialectWithJsonSupport
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache:
        use_second_level_cache: true
        use_query_cache: true
        use_minimal_puts: true
        region:
          factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        hazelcast:
          use_lite_member: true
          instance_name: cef-hazelcast-cache
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
