spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.20.2.35:5432/CEF
    username: cef
    password: cef_fall2017
    tomcat:
      fairQueue: true
      jmx-enabled: false
      initialSize: 5
      maxActive: 10
      maxIdle: 10
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: select 1
      validationQueryTimeout: 10
      maxWait: 30000
  mail:
    host: CDXDMAIL01.cloud.epacdx
    port: 25
    properties:
      mail:
        smtp:
          auth: false
cdx:
  registerEndpointConfiguration:
    serviceUrl: https://devngn.epacdxnode.net/cdx-register-II/services/RegisterService
  registerProgramFacilityEndpointConfiguration:
    serviceUrl: https://devngn.epacdxnode.net/cdx-register-II/services/RegisterProgramFacilityService
  registerSignEndpointConfiguration:
    serviceUrl: https://devngn.epacdxnode.net/cdx-register-II/services/RegisterSignService
  naas-token-url: https://naasdev.epacdxnode.net/xml/SecurityToken_v30.wsdl
  naas-user: caer-cef-admin@epa.gov
  naas-password: CDXcaercef01
  naas-ip: 127.0.0.1
  cdx-base-url: https://dev.epacdx.net
  allowed-origins:
    - https://cdx.epa.gov
    - https://cdxnodengn.epa.gov
    - https://test.epacdx.net
    - https://testngn.epacdxnode.net
    - https://dev.epacdx.net
    - https://devngn.epacdxnode.net
    - https://dev.e-enterprise.gov
    - https://dev2.e-enterprise.gov
    - https://test.e-enterprise.gov
    - https://test2.e-enterprise.gov
    - https://e-enterprise.gov
    - https://www2.e-enterprise.gov
excel-parser:
  base-url: https://devngn.epacdxnode.net/excel-json-parser/api/v1
virus-scanner:
  endpoint: https://cdxtools.epa.gov/xml/VirusScan.wsdl
ga:
  slt-email: edward.canoles@cgifederal.com
network-nodes:
  eis:
    serviceUrl: https://devngn.epacdxnode.net/ngn-enws20/services/NetworkNode2Service
    dataflow: EIS
