export enum EntityType {
    EMISSION = 'EMISSION',
    EMISSIONS_PROCESS = 'EMISSIONS_PROCESS',
    EMISSIONS_REPORT = 'EMISSIONS_REPORT',
    EMISSIONS_UNIT = 'EMISSIONS_UNIT',
    FACILITY_SITE = 'FACILITY_SITE',
    OPERATING_DETAIL = 'OPERATING_DETAIL',
    RELEASE_POINT = 'RELEASE_POINT',
    REPORTING_PERIOD = 'REPORTING_PERIOD',
    CONTROL_PATH = 'CONTROL_PATH',
    CONTROL = 'CONTROL',
    REPORT_ATTACHMENT = 'REPORT_ATTACHMENT'
}
