export enum EntityType {
    EMISSION = 'EMISSION',
    EMISSIONS_PROCESS = 'EMISSIONS_PROCESS',
    EMISSIONS_REPORT = 'EMISSIONS_REPORT',
    EMISSIONS_UNIT = 'EMISSIONS_UNIT',
    FACILITY_SITE = 'FACILITY_SITE',
    OPERATING_DETAIL = 'OPERATING_DETAIL',
    REPORTING_PERIOD = 'REPORTING_PERIOD'
}
