import { BaseCodeLookup } from 'src/app/shared/models/base-code-lookup';
import { EmissionUnit } from 'src/app/shared/models/emission-unit';
import { ReleasePoint } from 'src/app/shared/models/release-point';
import { EmissionsReport } from 'src/app/shared/models/emissions-report';
import { FacilitySiteContact } from 'src/app/shared/models/facility-site-contact';
import { FacilityNaicsCode } from 'src/app/shared/models/facility-naics-code';
import { Control } from 'src/app/shared/models/control';
import { FipsCounty } from 'src/app/shared/models/fips-county';
import { FipsStateCode } from 'src/app/shared/models/fips-state-code';
import { InventoryYearCodeLookup } from './inventory-year-code-lookup';

export class FacilitySite {
  id: number;
  name: string;
  latitude: number;
  longitude: number;
  streetAddress: string;
  city: string;
  stateCode: FipsStateCode;
  postalCode: string;
  countyCode: FipsCounty;
  mailingStreetAddress: string;
  mailingCity: string;
  mailingStateCode: FipsStateCode;
  mailingPostalCode: string;
  operatingStatusCode: BaseCodeLookup;
  facilityNAICS: FacilityNaicsCode[];
  emissionsReport: EmissionsReport;
  emissionsUnits: EmissionUnit[];
  releasePoints: ReleasePoint[];
  controls: Control[];
  contacts: FacilitySiteContact[];
  tribalCode: BaseCodeLookup;
  programSystemCode: BaseCodeLookup;
  statusYear: number;
  altSiteIdentifier: string;
  facilityCategoryCode: BaseCodeLookup;
  facilitySourceTypeCode: InventoryYearCodeLookup;
  description: string;
  comments: string;
}
