--cef-105 test data for emissions_report
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'Certified', 2013, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'Failed', 2014, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'InProgress', 2015, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'NotStarted', 2016, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'Passed', 2017, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'PassedAlerts', 2018, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('2774511', 'Pending', 2019, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('9758611', 'Certified', 2016, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('9758611', 'Certified', 2017, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('9758611', 'Certified', 2018, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);
INSERT INTO emissions_report(facility_id, status, year, created_by, created_date, last_modified_by, last_modified_date) VALUES ('9758611', 'InProgress', 2019, 'THOMAS.FESPERMAN', current_timestamp, 'THOMAS.FESPERMAN', current_timestamp);